name: CI - Fintech Review Scraper

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint scripts
        run: |
          flake8 scripts/ --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Check notebooks
        run: |
          pip install nbconvert
          for notebook in $(find notebooks/ -name "*.ipynb"); do
            echo "Validating $notebook"
            jupyter nbconvert --to notebook --execute "$notebook" --stdout > /dev/null || true
          done
